name: mapapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    #? start packages
  flutter_bloc: ^8.0.1
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cupertino_icons: ^1.0.2
    #? end packages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

